#设置端口号
server:
  port: 9000

#设置应用名字
spring:
  application:
    name: api-gateway

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#网关设置
zuul:
  routes:
    product-service: /api-gateway/product/**
    order-service: /api-gateway/order/**
  ignored-patterns: /*-service/**
  #设置脱敏头信息为空，否则cookie等敏感信息不能传递
  sensitive-headers:

