#设置端口号
server:
  port: 9000

#设置应用名字
spring:
  application:
    name: api-gateway

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#网关设置
zuul:
  routes:
    product-service: /api-gateway/**
    order-service: /api-gateway/**
  #服务隔离，避免开放默认服务
  ignored-patterns: /*-service/**
  #应用隔离，指定应用不走网关
  #ignored-services: product-service


