server:
  port: 8781

spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  #zipkin注册地址
  zipkin:
    base-url: http://10.4.122.7:9411/
    sender:
      type: web
  #设置采样百分比：开发环境配置1，生产环境就用默认
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#设置自定义负载策略
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#设置超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 1000
  hystrix:
    enabled: true

#设置hystrix超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

#暴露全部监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"