#应用端口
server:
  port: 9100
#应用名称
spring:
  application:
    name: config-server
  #git地址
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wangchong250/config-cloud.git
          username: m13478440042@163.com
          password: 1qaz!QAZ
          timeout: 5
          default-label: master
#注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



